
<?php
	echo "<h3 style='text-align:center;font-size: 35px;'>Login</h3>";
	echo $this->loginForm;
	echo "<p class='alert_login'>$this->errorMessage</p>";
?>	
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title></title>
	<link rel="stylesheet" href="">
</head>
<body>
	<div class="dangky" style=""><a href="<?=$this->url(array('controller'=>'index','action'=>'dangky1'))?>">Register</a></div>
</body>
</html>
