<?php 
	$this->title = "Register";
	$this->headTitle($this->title);
	echo $this->form;
	echo "<p class='dangky_canhbao'>$this->errorMessage</p>";
?>
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title></title>
	<link rel="stylesheet" href="">
</head>
<body>
	<div class="check_login" style=""><a href="<?=$this->url(array('controller'=>'index','action'=>'dangnhap'))?>">Login</a></div>
</body>
</html>